services:
  db:
    image: postgres:17
    container_name: edu-hotel-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: edu_hotel
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: edu-hotel-backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgrespw@db:5432/edu_hotel?schema=public
      JWT_SECRET: your_secret_here
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
