services:
  db:
    image: postgres:15-alpine
    container_name: db-${PROJECT_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
    expose:
      - "5432"
    networks:
      - internal

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: backend-${PROJECT_NAME}
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Backend'in hangi yoldan geldiğini bilmesi gerekebilir
      SERVER_SERVLET_CONTEXT_PATH: ${BASE_PATH}-api 
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
    networks:
      - internal

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    container_name: frontend-${PROJECT_NAME}
    environment:
      # Önemli: React/Vue/NextJS'e alt yolu bildirin
      PUBLIC_URL: ${BASE_PATH} 
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
